// constants.js
export const GAME_CONSTANTS = {
    TILE_SIZE: 32,
    CANVAS_WIDTH_TILES: 10,
    CANVAS_HEIGHT_TILES: 10,
    POKOTA_MOVE_SPEED_PX: 4,
    POKOTA_ANIM_FRAME_DURATION: 8,
    ZOMBIE_ATTACK_RANGE_TILES: 5,
    PROJECTILE_SPEED: 5,
    ATTACK_INTERVAL: 1000,
    POKOTA_MAX_HP: 100,
    ZOMBIE_MELEE_DAMAGE: 5,
    ZOMBIE_ATTACK_COOLDOWN: 500,
    POKOTA_SAFE_DISTANCE_TILES: 3, // 胖波與怪物保持的安全距離 (磁磚數)
    ZOMBIE_ATTACK_RANGE_PX: 1.5 * 32 // 僵屍的攻擊範圍 (像素)
};
